# Generated by Django 5.2.8 on 2025-11-22 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='frutables',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='fruits/'),
        ),
    ]
